# Generated by Django 3.2.7 on 2021-10-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_lists', '0002_auto_20211020_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority_level',
            field=models.IntegerField(default=1),
        ),
    ]
