# Generated by Django 3.2.7 on 2021-10-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_lists', '0004_remove_project_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='member',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
