# Generated by Django 3.2.7 on 2021-10-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='wiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myer', models.FileField(upload_to='wikis')),
                ('JB', models.FileField(upload_to='wikis')),
                ('DJ', models.FileField(upload_to='wikis')),
                ('cottonon', models.FileField(upload_to='wikis')),
                ('workplace', models.FileField(upload_to='wikis')),
                ('equal', models.FileField(upload_to='wikis')),
                ('conduct', models.FileField(upload_to='wikis')),
                ('leave', models.FileField(upload_to='wikis')),
            ],
        ),
    ]
