# Generated by Django 3.2.7 on 2021-10-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_wiki'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wiki',
            old_name='DJ',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='wiki',
            name='JB',
        ),
        migrations.RemoveField(
            model_name='wiki',
            name='conduct',
        ),
        migrations.RemoveField(
            model_name='wiki',
            name='cottonon',
        ),
        migrations.RemoveField(
            model_name='wiki',
            name='equal',
        ),
        migrations.RemoveField(
            model_name='wiki',
            name='leave',
        ),
        migrations.RemoveField(
            model_name='wiki',
            name='myer',
        ),
        migrations.RemoveField(
            model_name='wiki',
            name='workplace',
        ),
    ]
