# Generated by Django 3.2.7 on 2021-10-13 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_resource_resource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='end_date',
            new_name='due_date',
        ),
        migrations.RemoveField(
            model_name='done',
            name='name',
        ),
        migrations.AddField(
            model_name='done',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='done',
            name='text',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='in_progress',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='in_progress',
            name='text',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='to_do',
            name='text',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='done',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='in_progress',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='to_do',
            name='details',
            field=models.TextField(),
        ),
    ]
