# Generated by Django 3.2.7 on 2021-10-19 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20211013_1142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='done',
        ),
        migrations.RemoveField(
            model_name='in_progress',
            name='name',
        ),
        migrations.DeleteModel(
            name='project',
        ),
        migrations.DeleteModel(
            name='resource',
        ),
        migrations.DeleteModel(
            name='team',
        ),
        migrations.DeleteModel(
            name='wiki',
        ),
        migrations.DeleteModel(
            name='in_progress',
        ),
        migrations.DeleteModel(
            name='to_do',
        ),
    ]
